version: '2'
services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  backend:
    build: ./bdev-backend/
    ports:
      - "6200:6200"
      - "4000:4000"
    volumes:
      - ./bdev-backend:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    build: ./bdev-frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./bdev-frontend:/usr/src/app
    depends_on:
      - backend
